# This rule is not used by the project geist-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over geistconnectors.doteich.com.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: geist-operator
    app.kubernetes.io/managed-by: kustomize
  name: geistconnector-admin-role
rules:
- apiGroups:
  - geistconnectors.doteich.com
  resources:
  - geistconnectors
  verbs:
  - '*'
- apiGroups:
  - geistconnectors.doteich.com
  resources:
  - geistconnectors/status
  verbs:
  - get
