apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: geist-operator
  name: geist-operator-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: geist-operator-manager-role
subjects:
- kind: ServiceAccount
  name: geist-operator-controller-manager
  namespace: {{ .Release.Namespace }}
