apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: geist-operator
  name: geist-operator-geistconnector-viewer-role
rules:
- apiGroups:
  - geistconnectors.config.geist-iot.com
  resources:
  - geistconnectors
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - geistconnectors.config.geist-iot.com
  resources:
  - geistconnectors/status
  verbs:
  - get
