apiVersion: geistconnectors.config.geist-iot.com/v1alpha
kind: GeistConnector
metadata:
  labels:
    app.kubernetes.io/name: geist-operator
    app.kubernetes.io/managed-by: kustomize
  name: geistconnector-sample
spec:
  # TODO(user): Add fields here
