{{ if .Values.redpanda.enabled }}

apiVersion: cluster.redpanda.com/v1alpha2
kind: Redpanda
metadata:
  name: redpanda
  namespace: {{.Release.Namespace}}
  labels:
    app.kubernetes.io/name: geist-redpanda
spec:
  clusterSpec:
    external:
      enabled: true
      domain: localhost
      type: NodePort
    statefulset:
      replicas: 1
      initContainers:
        setDataDirOwnership:
          enabled: false
    enterprise: null

{{ end }}